hw7 (jdi) first attempt
Liliya-web/LiliiaIskanderova pull request #6
Opened 2021-07-11 19:50 UTC by Liliya-web

2021-07-13 21:45 UTC, pnatashap requested changes
Замечания в тексте

2021-07-13 21:45 UTC, pnatashap commented on src/test/java/ru/training/at/hw7/listeners/TestNGListener.java
> +public class TestNGListener implements IInvokedMethodListener {    private Safe<Long> start = new Safe<>(0L);
перенос строки потерялся

2021-07-13 21:45 UTC, pnatashap commented on src/test/java/ru/training/at/hw7/listeners/TestNGListener.java
> +    public void afterInvocation(IInvokedMethod method, ITestResult tr) {
а это точно нужно? для чего оно используется и можно ли остаться со скриштом без этого кода?

2021-07-13 21:45 UTC, pnatashap commented on src/test/java/ru/training/at/hw7/tests/SubmitMetalsAndColorsFormTest.java
> +        String dataFile = "/home/liliya/IdeaProjects/LiliiaIskanderova/src/test/resources/ru.training.at.hw7/"
полные пути к файлам использовать нельзя! тесты - это всегда то, что должны без проблем собрать и использовать все в проекте, а тут оно получается только на твоей машине может собраться - не хорошо.
используем или относительные пути или пути из параметров.

2021-07-13 21:45 UTC, pnatashap commented on src/test/java/ru/training/at/hw7/tests/SubmitMetalsAndColorsFormTest.java
> +    public void submitMetalsAndColorsFormTest(List<Double> summary, List<String> elements,
а почему List<Double> summary? 
Double очень опасно использовать, если есть запятые, региональные настройки могут прочитать реально дробное число, если числа через запятую написаны. 
Если известно, что число целое, надо использовать целое.

2021-07-14 21:51 UTC, pnatashap approved these changes
гораздо лучше.
но на один вопрос так и нет ответа

2021-07-14 21:51 UTC, pnatashap commented on src/test/java/ru/training/at/hw7/listeners/TestNGListener.java
> +    public void afterInvocation(IInvokedMethod method, ITestResult tr) {
так можно ли и скриншот получить и листенер не писать?

2021-07-14 21:51 UTC, pnatashap commented on src/test/resources/test.properties
> +#screenshot.strategy=off | on failure | on assert | new page | flow
jdi умеет делать скриншоты при падении теста.
но всегда ли они будут?

2021-07-15 03:35 UTC, Liliya-web commented on src/test/java/ru/training/at/hw7/listeners/TestNGListener.java
> +    public void afterInvocation(IInvokedMethod method, ITestResult tr) {
Я знаю, что можно написать другой листенер. Для аллюра. Который имплементит ITestListener, прооверрайдить там метод onTestFailure() и создать метод с аннотацией @Attachment, который вызывается из метода onTestFailure(). Это, если нам нужны скриншоты только при падении. Или как-то можно прикладывать вообще без листенеров?

2021-07-15 03:41 UTC, Liliya-web commented on src/test/resources/test.properties
> +#screenshot.strategy=off | on failure | on assert | new page | flow
Можно сделать screenshot/strategy=off, тогда скриншотов не будет. Если сделать on, то будут и при падении и при успешном прохождении тестов

2021-07-16 05:34 UTC, merged